server:
  port: 19000

# mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qian_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: zhangqian
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4GEPT8NWiyhQ3XHtbWRG
      secret-key: o7gDXT6RfY8H9udojWZviW4ySGYbaI
      oss:
        endpoint: oss-cn-zhangjiakou.aliyuncs.com
        bucket: qian-mall
  application:
    name: mall-product
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: 1
      logic-not-delete-value: 0
logging:
  level:
    com.qian.mall: debug